### ISSUE TITLE
could you tell something about your role?

### ISSUE THREAD

**Issue by DO1JLR** [toshywoshy/ansible-role-icinga2#1]
Hi there

I am just looking which ansible roles I should take for my icinga2 setup and by chance I came across your video: https://www.youtube.com/watch?v=yNnq-JNS2gk

Now I was thinking if the roles you wrote are the right choice.
But based on the fact that the last commit in this repo was a while ago and there is not even a README available I wonder if the role shown here is production ready and if you could say something about dependencies, variables and an example how to use them best.

thanks

**Comment by toshywoshy** [comment]
Hey,

The role here on github is production ready, and is our own role we use to roll out Icinga2, but made abstract, in the sense that variables are not predefined and some of our own architecture files have been omitted.

However I am in the process of refactoring the whole role to add eg IcingaDB, Grafana, ... to be more up to date and add other back-end or front-end we now use.
Most of our development is done on our own git system and then I make it abstract and pushed here to github, however that is not our focus.

Also a lot of the Ansible role syntax has changed over the years, and while this will still work with Ansible 2.9 and Ansible 2.10, I suspect it will break with newer versions.
In addition some of the Icinga2 syntax can also be optimized and made more robus, again here it will work with current version, however Icinga2 has made some changes to be more flexible and while we incorperated that in our own role, I haven't put that all online here at github.

If you're going to use this, I could update the role, just remember that most of it is based on how we deploy our Icinga2 systems.

Regards,
Toshaan.
